// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transformese.Data;

#nullable disable

namespace Transformese.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205094309_AdicionandoMaisUmCampoDaTriagem")]
    partial class AdicionandoMaisUmCampoDaTriagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transformese.Domain.Entities.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceitouNovidades")
                        .HasColumnType("bit");

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("bit");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CursoInteresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deficiencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escolaridade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentidadeGenero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JaEstudouNaGF")
                        .HasColumnType("bit");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeIndicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeOngResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacoesONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrientacaoSexual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfilLinkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PessoasNaCasa")
                        .HasColumnType("int");

                    b.Property<int?>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<bool>("PossuiComputador")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiInternet")
                        .HasColumnType("bit");

                    b.Property<string>("RacaCor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RendaFamiliar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrabalhaAtualmente")
                        .HasColumnType("bit");

                    b.Property<string>("TurnoPreferido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VagaEncaminhada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAdministrador")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2025, 12, 5, 6, 43, 9, 129, DateTimeKind.Local).AddTicks(9566),
                            DataNascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EhAdministrador = true,
                            Email = "admin@admingerando.falcoes",
                            Nome = "Admin",
                            Senha = "$2a$11$4LHWGMUAqH1mFegwo7pXm.Gal0yVc3woBL1SQePF.yEZdsoUc9/j2",
                            Sexo = "Outro",
                            Sobrenome = "Geral"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
