// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transformese.Data;

#nullable disable

namespace Transformese.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transformese.Domain.Entities.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEntrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacoesGF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacoesONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfilLinkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PossuiComputador")
                        .HasColumnType("bit");

                    b.Property<bool>("PossuiInternet")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("UnidadeId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.CandidatoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("NovoStatus")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CandidatoLogs");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("DescricaoTipoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            IdTipoUsuario = 1,
                            DescricaoTipoUsuario = "Administrador"
                        },
                        new
                        {
                            IdTipoUsuario = 2,
                            DescricaoTipoUsuario = "Candidato"
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Bairro = "São Miguel",
                            Cidade = "São Paulo",
                            Endereco = "Rua A, 100",
                            Estado = "SP",
                            Nome = "Unidade São Miguel",
                            Responsavel = "Maria da Silva",
                            UnidadeId = -1
                        },
                        new
                        {
                            Id = -2,
                            Bairro = "Itaquera",
                            Cidade = "São Paulo",
                            Endereco = "Av B, 200",
                            Estado = "SP",
                            Nome = "Unidade Itaquera",
                            Responsavel = "João Santos",
                            UnidadeId = -2
                        },
                        new
                        {
                            Id = -3,
                            Bairro = "Tatuapé",
                            Cidade = "São Paulo",
                            Endereco = "Rua C, 300",
                            Estado = "SP",
                            Nome = "Unidade Tatuapé",
                            Responsavel = "Fernanda Lima",
                            UnidadeId = -3
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Admin do Sistema",
                            Senha = "123456",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            IdUsuario = 6,
                            DataNascimento = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato1@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 1",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 7,
                            DataNascimento = new DateTime(2000, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato2@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 2",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 8,
                            DataNascimento = new DateTime(2000, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato3@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 3",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 9,
                            DataNascimento = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato4@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 4",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 10,
                            DataNascimento = new DateTime(2000, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato5@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 5",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 11,
                            DataNascimento = new DateTime(2000, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato6@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 6",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 12,
                            DataNascimento = new DateTime(2000, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato7@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 7",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 13,
                            DataNascimento = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato8@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 8",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 14,
                            DataNascimento = new DateTime(2000, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato9@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 9",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 15,
                            DataNascimento = new DateTime(2000, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato10@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 10",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 16,
                            DataNascimento = new DateTime(2000, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato11@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 11",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 17,
                            DataNascimento = new DateTime(2000, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato12@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 12",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 18,
                            DataNascimento = new DateTime(2000, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato13@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 13",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 19,
                            DataNascimento = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato14@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 14",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            IdUsuario = 20,
                            DataNascimento = new DateTime(2000, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "candidato15@sistema.com",
                            FotoPerfil = "default-user.jpg",
                            Nome = "Candidato 15",
                            Senha = "123456",
                            TipoUsuarioId = 2
                        });
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Candidato", b =>
                {
                    b.HasOne("Transformese.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.CandidatoLog", b =>
                {
                    b.HasOne("Transformese.Domain.Entities.Candidato", "Candidato")
                        .WithMany("HistoricoLogs")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transformese.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Candidato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Transformese.Domain.Entities.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("HistoricoLogs");
                });

            modelBuilder.Entity("Transformese.Domain.Entities.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
